apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: JWT_SECRET
              value: this_is_a_very_long_and_secure_jwt_secret_key_123456
            - name: SPRING_DATASOURCE_PASSWORD
              value: Riju@03Rai@07
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/flight_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: api-gateway
          name: api-gateway-1
          ports:
            - containerPort: 8062
              protocol: TCP
      restartPolicy: Always
