apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: booking-service
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: booking-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: booking-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_DATASOURCE_PASSWORD
              value: Riju@03Rai@07
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/booking_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: booking-service
          name: booking-service-1
          ports:
            - containerPort: 9002
              protocol: TCP
      restartPolicy: Always
